const path = require('path');
const ToolBridge = require('./tool-bridge');
const defaultFixers = require('../../../scripts/scripts/fixers/index.cjs');

/**
 * Runs adaptive fixers based on findings produced by the analysis pipeline.
 */
class FixerRunner {
  constructor({ projectRoot, enableWrites = false, fixers = defaultFixers } = {}) {
    this.projectRoot = projectRoot;
    this.enableWrites = enableWrites;

    this.toolBridge = new ToolBridge({
      workingDirectory: projectRoot,
      enableFileOperations: true,
      enableBackups: true
    });

    this.fixersByCategory = this.buildIndexer(fixers);
    this.metrics = {
      attempted: 0,
      applied: 0,
      skipped: 0,
      errors: []
    };
  }

  buildIndexer(fixerList) {
    return fixerList.reduce((acc, fixer) => {
      fixer.matchCategories.forEach(category => {
        if (!acc[category]) {
          acc[category] = [];
        }
        acc[category].push(fixer);
      });
      return acc;
    }, {});
  }

  /**
   * Applies fixers to the provided report.
   * @param {object} finalReport - report generated by CodeTitanOrchestration.
   * @param {object} [options]
   * @returns {Promise<object>} - summary of fixer execution.
   */
  async applyFixes(finalReport, options = {}) {
    const { topIssues = [] } = finalReport;
    const processedFiles = new Set();

    for (const issue of topIssues) {
      const fixers = this.fixersByCategory[issue.category] || [];
      if (fixers.length === 0) {
        this.metrics.skipped++;
        continue;
      }

      const relativePath = path.relative(this.projectRoot, issue.file);
      if (relativePath.startsWith('..')) {
        this.metrics.errors.push({
          issue,
          error: `File ${issue.file} is outside project root ${this.projectRoot}`
        });
        continue;
      }

      for (const fixer of fixers) {
        this.metrics.attempted++;
        try {
          const result = await fixer.apply({
            filePath: relativePath,
            issue,
            projectRoot: this.projectRoot,
            toolBridge: this.toolBridge,
            options: {
              enableWrites: this.enableWrites,
              ...options
            }
          });

          if (result?.applied) {
            this.metrics.applied++;
            processedFiles.add(relativePath);
          } else {
            this.metrics.skipped++;
          }
        } catch (error) {
          this.metrics.errors.push({ issue, error: error.message });
        }
      }
    }

    return {
      ...this.metrics,
      filesTouched: Array.from(processedFiles)
    };
  }
}

module.exports = FixerRunner;
